#define FRONT_LEFT_MTR_PRT -20
#define FRONT_RIGHT_MTR_PRT 17
#define BACK_LEFT_MTR_PRT -19
#define BACK_RIGHT_MTR_PRT 18
#define INTAKE_A_MTR_PRT -12
#define INTAKE_B_MTR_PRT -13
#define CATAPULT_A_MTR_PRT 15
#define CATAPULT_B_MTR_PRT 14

#define IMU_PORT 1
#define CATAPULT_LIMIT_PORT 0
