#define FRONT_LEFT_MTR_PRT -20
#define FRONT_RIGHT_MTR_PRT 17
#define MIDDLE_LEFT_MTR_PRT -10
#define MIDDLE_RIGHT_MTR_PRT 9
#define BACK_LEFT_MTR_PRT -19
#define BACK_RIGHT_MTR_PRT 18
#define INTAKE_A_MTR_PRT -11
#define INTAKE_B_MTR_PRT -12
#define CATAPULT_A_MTR_PRT 13
#define CATAPULT_B_MTR_PRT 14

#define IMU_PORT 16
#define CATAPULT_LIMIT_PORT 'H'
